hydra:
  run:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${name}_${experiment}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - env=FetchPickAndPlace-v4,AntMaze_UMaze-v3,PointMaze_UMaze-v3
    - seed=1
    - mode=baseline,sac_her,sac_her_svgg
    - num_of_epochs=1
  job:
    name: train
    chdir: null
    override_dirname: env=FetchPickAndPlace-v4,AntMaze_UMaze-v3,PointMaze_UMaze-v3,mode=baseline,sac_her,sac_her_svgg,num_of_epochs=1,seed=1
    id: ???
    num: ???
    config_name: train
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: C:\Users\aaron\Desktop\Projects\New folder (2)\multi-goal-rl-svgg
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: C:\Users\aaron\Desktop\Projects\New folder (2)\multi-goal-rl-svgg\config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      mode: baseline
      goal_setter: svgg
      agent: sac
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
agent:
  _target_: algorithm.agent.continuous_action.sac.sac.SACAgent
  obs_dim: 0
  action_dim: 0
  action_range: null
  device: ${device}
  critic_cfg:
    _target_: algorithm.agent.continuous_action.sac.critic.DoubleQCritic
    obs_dim: ${agent.obs_dim}
    action_dim: ${agent.action_dim}
    hidden_dim: 1024
    hidden_depth: 2
    log_frequency: ${log_frequency}
  actor_cfg:
    _target_: algorithm.agent.continuous_action.sac.actor.DiagGaussianActor
    obs_dim: ${agent.obs_dim}
    action_dim: ${agent.action_dim}
    hidden_depth: 2
    hidden_dim: 1024
    log_std_bounds:
    - -5
    - 2
    log_frequency: ${log_frequency}
  discount: 0.99
  init_temperature: 0.1
  alpha_lr: 0.0001
  alpha_betas:
  - 0.9
  - 0.999
  actor_lr: 0.0001
  actor_betas:
  - 0.9
  - 0.999
  actor_update_frequency: 1
  critic_lr: 0.0001
  critic_betas:
  - 0.9
  - 0.999
  critic_tau: 0.005
  critic_target_update_frequency: 2
  batch_size: 1024
  learnable_temperature: true
goal_setter:
  _target_: algorithm.goal_setter.svgg.SVGG.SVGG
  nG: ${nG}
  num_traj: 10
  goals_init: 5000
  num_of_goals: 1000
  LR_ANOMALY: 0.001
  LR_SKILLS: 0.001
  LR_SVGG: 0.001
  BATCH_R: 100
  BATCH_S: 100
  SKILLS_ITTR: 200
  ALPHA: 2.0
  BETA_P: 2.0
  TEMPERATURE: 0.1
  NUM_SVGD_STEPS: 10
  anomaly_model:
    _target_: algorithm.goal_setter.svgg.anomalygoal.AnomalyDetector
    input_dim: ${nG}
    hidden_layers:
    - 1024
    - 1024
    log_frequency: 1
  skills_model:
    _target_: algorithm.goal_setter.svgg.skillspredictor.SkillsPredictorModel
    nG: ${nG}
    layers:
    - 1024
    - 1024
    log_frequency: 1
  device: ${device}
  debug: ${debug}
  particle_eval_frequency: ${particle_eval_frequency}
mode:
  use_goal_setter: false
  use_hindsight: false
env: FetchPickAndPlace-v4
nS: ???
nG: ???
nA: ???
name: robotic_control
project_name: goal_RL_robotic_control
experiment: test
num_train_steps: 100000.0
replay_buffer_capacity: ${num_train_steps}
num_traj: 10
num_seed_steps: 100000.0
eval_frequency: 2
num_eval_episodes: 2
use_hindsight: false
use_goal_setter: false
num_of_epochs: 1
device: ${cuda_if_available:}
log_frequency: 100
particle_eval_frequency: 100
seed: 1
debug: false
checkpoint_dir: checkpoints
checkpoint_frequency: 0
save_final: true
