

_target_: algorithm.agent.continuous_action.sac.sac.SACAgent

obs_dim: 0
action_dim: 0
action_range: null
device: ${device}
critic_cfg:
  _target_: algorithm.agent.continuous_action.sac.critic.DoubleQCritic
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_dim: 1024
  hidden_depth: 2
  log_frequency: ${log_frequency}
  
actor_cfg:
  _target_: algorithm.agent.continuous_action.sac.actor.DiagGaussianActor
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_depth: 2
  hidden_dim: 1024
  log_std_bounds: [-5, 2]
  log_frequency: ${log_frequency}
discount: 0.99
init_temperature: 0.1
alpha_lr: 1e-4
alpha_betas: [0.9, 0.999]
actor_lr: 1e-4
actor_betas: [0.9, 0.999]
actor_update_frequency: 1
critic_lr: 1e-4
critic_betas: [0.9, 0.999]
critic_tau: 0.005
critic_target_update_frequency: 2
batch_size: 1024
learnable_temperature: true
  
